### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by pebneter** [archfish/pulsar_sdk#10]
Hi!
It looks like there was not a lot of activity in this repository for the last years.
Is this project still active? If no, can you recommend another ruby pulsar client?

**Comment by archfish** [comment]
Sorry, I don't have time to maintain. Basic function may work for latest pulsar server.

Can see if https://github.com/maximebedard/pulsar-client-ruby can work.

**Comment by pebneter** [comment]
ok, thanks for the link!
