### ISSUE TITLE
发布到 Rubygems.org

### ISSUE THREAD

**Issue by wppurking** [archfish/pulsar_sdk#4]
你好, 我在寻找 pulsar 的 ruby sdk 的 gem 寻找到这里, 已经看到这个 gem 在 github 上发布了 4 个版本, 现在最新的是 0.7.2, 但是在 [rubygems.org](https://rubygems.org/search?utf8=%E2%9C%93&query=pulsar) 上并没有此 gem, 是否考虑将当前 gem 发布到 rubygems.org 上呢?

**Comment by archfish** [comment]
Before version 1.0 release there will be many changes on api. 

I'm planning push to rubygems.org after 1.0 release.

**Comment by archfish** [comment]
TBD

**Comment by archfish** [comment]
@wppurking just publish to rubygem check this [pulsar_sdk](https://rubygems.org/gems/pulsar_sdk)

**Comment by wppurking** [comment]
Great!  
Thanks
